### ISSUE TITLE
New feature: Vertical display

### ISSUE THREAD

**Issue by noowa** [marcelodolza/iziToast#154]
Hi dolce,

First of all, congratulations for your work, it is really incredible and useful.

I was thinking about the possibility of having a vertical orientation option (eg: vertical: true, default false). I'm thinking about using the toast as a sort of navigation bar and place it in left or right of the page. The problem with the current toasts is that the icon, title, and close button appear horizontally. Even though I can "create" the navigation menu with HTML inside the toast message, the other internal items of the toast are not placed vertically (one on top of the other).

I don't know if there is already the possibility of configuring the toasts as described above.

Do you think it is possible to do something similar? If you need any additional information please let me know.

Regards

**Comment by Harrmalik** [comment]
Can you give an example of this?
