### ISSUE TITLE
.scss

### ISSUE THREAD

**Issue by nam-co** [marcelodolza/iziToast#156]
Hi Dolce, since the new sass version, .css can't be imported, so I was wondering if its possible to duplicate the "dist/css/iziToast.css" into a .scss file, so it can be imported correctly, appreciate any help

thanks

**Comment by tvaliasek** [comment]
Im using dart-sass implementation and import is ok, just import css file without extension.

`@import "../node_modules/izitoast/dist/css/iziToast";`

**Comment by Libida** [comment]
But use of .css will not support any sass features, e.g. when you need to add parent class to all styles inside (can be needed when you work with 3rd parties so there will be no conflicts in styling), e.g.
.yourSpace {
...
@import "../node_modules/izitoast/dist/css/iziToast";
...
}

In this case .yourSpace won't be added, if this would be sass file - would.

**Comment by marcelodolza** [comment]
I will be adding support for sass in the next update. thanks.
