### ISSUE TITLE
Doesn't work on tablet

### ISSUE THREAD

**Issue by csandreas1** [marcelodolza/iziToast#167]
This plugin doesn't work on my tablet model (SM-T535)

On desktop device it works fine though.

Here is how i call it:

`iziToast.success({ title: 'OK',position:'center',drag:true, message: '"&eMunDictionary("WBB_IZITOAST_SUCCESS")&"', });`

**Comment by kawaaii** [comment]
Is Javascript enabled on the browser for that device?
