### ISSUE TITLE
Question : Function to close notification

### ISSUE THREAD

**Issue by fakhamatia** [marcelodolza/iziToast#174]
Hello and thank you for this great work.

`iziToast.info({`
`        position: "center",`
 `       title: "please wait.",`
  `      timeout: false,`
`    });`

How can i set a function to close this notification?
I read doc but i don't get it.

**Comment by kawaaii** [comment]
If you have read the documentation, you would have noticed that there is a function to kill all toasts
`iziToast.destroy();`
