### ISSUE TITLE
iziToast message not getting displayed

### ISSUE THREAD

**Issue by goktugozleyen** [marcelodolza/iziToast#181]
![2019-06-20 (1)](https://user-images.githubusercontent.com/43008815/59866022-33cc1880-9393-11e9-805c-911912d0b686.png)
![2019-06-20](https://user-images.githubusercontent.com/43008815/59866024-33cc1880-9393-11e9-8724-31a5ebe94fa9.png)

As u can see iziToast working but not getting displayed. I'm using the latest version

**Comment by YusifKhalilov** [comment]
Kardeş sen kod parçası göstersen daha iyi olur. Sorunun nerede olduğunu göre bilmek için.

**Comment by huntleight** [comment]
Hata yok aslında sadece görüntüye yansımıyor. Console kısmında iziToast-opened classlarının falan aktif olduğunu fakat gözle gözükmediğini göstermek istedim.

**Comment by marcelodolza** [comment]
It seems that the css was not imported correctly.
