### ISSUE TITLE
SASS (SCSS) version

### ISSUE THREAD

**Issue by mhrabiee** [marcelodolza/iziToast#182]
Hi,
First of all thanks for all the efforts.
Any plan to have SASS (SCSS) beside .styl? I'm wiling to port it and submitting as PR.

**Comment by adam-riha** [comment]
Hello,
I've made a PR #194 with sass port.

**Comment by marcelodolza** [comment]
Thanks @mhrabiee . I will update the repository soon.

**Comment by mhrabiee** [comment]
@marcelodolza Please update the repository and release new version
