### ISSUE TITLE
the dialog is cut off

### ISSUE THREAD

**Issue by bluedasher13** [marcelodolza/iziToast#188]
If height of the dialog is greater than height of window, the dialog will be cut off, and we can't scroll the page to see the whole dialog;

To fixed this problem, please add  `.iziToast-wrapper { overflow: auto; pointer-events: all; }` and `body { overflow: hidden; }` during the period of any dialog being visible.

**Comment by marcelodolza** [comment]
The idea of ​​toast notifications is to display quick messages, without blocking the user's scrolling.
Thank you.
