### ISSUE TITLE
IziToast is not defined in php

### ISSUE THREAD

**Issue by Chandupoorna** [marcelodolza/iziToast#196]
I am using izitoast to echo the notification in the php login page after the from is submitted i am getting the error like iziToast is not defined.I have succesfully imported the css and js files of izitoast

**Comment by F8ER** [comment]
> I am using izitoast to echo the notification in the php login page after the from is submitted i am getting the error like iziToast is not defined.I have succesfully imported the css and js files of izitoast

Are you sure you included the library correctly right before the PHP output-caller?
