### ISSUE TITLE
Dynamic message

### ISSUE THREAD

**Issue by AndrewPixel** [marcelodolza/iziToast#200]
I have a toast that is displayed for a relatively long time so I'd liked to periodically change the message. After the toast is displayed. I tried this:

```
let iziTxt = document.querySelector('.iziToast-message.slideIn');
iziTxt.innerHTML = "Still working...";
```
but the message didn't change. How can I change the message dynamically?

**Comment by F8ER** [comment]
How do you create a toast?

**Comment by AndrewPixel** [comment]
Sorry, after checking it numerous times I found that the toast I created and subsequently destroyed before displaying the current toast was being referenced. I added an ID to the current toast and I was able to reference (and change) the message correctly.
