### ISSUE TITLE
Documentation is unavailable

### ISSUE THREAD

**Issue by douglasdtc** [marcelodolza/iziToast#203]
The site, which contains the documentation is currently offline. I don't know if this is temporary or permanent, however, I can't find the documentation anywhere else. Is there an alternative repo with the docs?

**Comment by F8ER** [comment]
Might help: <https://web.archive.org/web/20210516125946/http://izitoast.marcelodolza.com/>

**Comment by douglasdtc** [comment]
Thank you @F8ER , it does help. The website is back up online now, but I'll keep the Web Archive in mind for future use. Thank you very much!
