### ISSUE TITLE
Cannot use FontAwesome

### ISSUE THREAD

**Issue by mkalinski93** [marcelodolza/iziToast#204]
Hey,

unfortunately, the icon just not appears.
I use set the icon value with "fas fa-check", even though "fa fa-check", "fa-check" and so on doesn´t work.
I can confirm that fontawesome works.

Have I forget something?

**Comment by fakhamatia** [comment]
Change the opacity to 1 in line [248](https://github.com/marcelodolza/iziToast/blob/ede716b98a14d65956760adde6c88275b9b1e613/dist/css/iziToast.css#L248).

**Comment by mkalinski93** [comment]
Thank you very much. It works :)
